#!/usr/bin/env python3
"""Export weights from web/mamba_nano.onnx to emulator/mamba_nano_weights.h."""

from pathlib import Path
import onnx
from onnx import numpy_helper
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
ONNX_PATH = ROOT / "web" / "mamba_nano.onnx"
OUT_HEADER = ROOT / "emulator" / "mamba_nano_weights.h"

def format_float_array(arr: np.ndarray, name: str, indent: str = "    ") -> str:
    flat = arr.flatten().astype(np.float32)
    lines = [f"static const float {name}[{len(flat)}] = {{"]
    chunk_size = 8
    for i in range(0, len(flat), chunk_size):
        chunk = flat[i : i + chunk_size]
        items = ", ".join(f"{v:.8e}f" for v in chunk)
        lines.append(f"{indent}{items},")
    lines.append("};\n")
    return "\n".join(lines)

def main():
    print(f"Loading ONNX model from {ONNX_PATH}...")
    model = onnx.load(str(ONNX_PATH))
    weights = {}
    for init in model.graph.initializer:
        weights[init.name] = numpy_helper.to_array(init)

    print(f"Loaded {len(weights)} initializers. Generating {OUT_HEADER}...")

    parts = [
        "/* Auto-generated by model/export_mamba_c.py - DO NOT EDIT MANUALLY */",
        "#ifndef MAMBA_NANO_WEIGHTS_H",
        "#define MAMBA_NANO_WEIGHTS_H",
        "",
        "#include <stdint.h>",
        "",
        "#define MAMBA_D_MODEL 64",
        "#define MAMBA_D_STATE 16",
        "#define MAMBA_DT_RANK 8",
        "#define MAMBA_NUM_LAYERS 2",
        "",
    ]

    # Projections
    parts.append("/* PC and Register Projections */")
    parts.append(format_float_array(weights["onnx::MatMul_263"], "MAMBA_W_PC_PROJ"))       # (32, 16)
    parts.append(format_float_array(weights["model.pc_proj.bias"], "MAMBA_B_PC_PROJ"))     # (16,)
    parts.append(format_float_array(weights["onnx::MatMul_264"], "MAMBA_W_REGS_PROJ"))     # (32, 48)
    parts.append(format_float_array(weights["model.regs_proj.bias"], "MAMBA_B_REGS_PROJ")) # (48,)

    # Layers
    for layer in range(2):
        parts.append(f"/* Layer {layer} Weights */")
        w_in = weights[f"onnx::MatMul_{265 if layer == 0 else 287}"]      # (64, 128)
        conv_w = weights[f"model.layers.{layer}.conv1d.weight"]            # (64, 1, 3)
        conv_b = weights[f"model.layers.{layer}.conv1d.bias"]              # (64,)
        w_xproj = weights[f"onnx::MatMul_{270 if layer == 0 else 292}"]   # (64, 40)
        w_dtproj = weights[f"onnx::MatMul_{283 if layer == 0 else 305}"]  # (8, 64)
        b_dtproj = weights[f"model.layers.{layer}.dt_proj.bias"]          # (64,)
        a_log = weights[f"model.layers.{layer}.A_log"]                     # (64, 16)
        d_param = weights[f"onnx::Mul_{285 if layer == 0 else 307}"].reshape(64) # (64,)
        w_outproj = weights[f"onnx::MatMul_{286 if layer == 0 else 308}"] # (64, 64)

        # For conv1d at t=0 with padding=2, only conv_w[:, 0, 2] is used
        conv_w_t0 = conv_w[:, 0, 2]

        parts.append(format_float_array(w_in, f"MAMBA_L{layer}_W_IN"))
        parts.append(format_float_array(conv_w_t0, f"MAMBA_L{layer}_CONV_W"))
        parts.append(format_float_array(conv_b, f"MAMBA_L{layer}_CONV_B"))
        parts.append(format_float_array(w_xproj, f"MAMBA_L{layer}_W_XPROJ"))
        parts.append(format_float_array(w_dtproj, f"MAMBA_L{layer}_W_DTPROJ"))
        parts.append(format_float_array(b_dtproj, f"MAMBA_L{layer}_B_DTPROJ"))
        parts.append(format_float_array(a_log, f"MAMBA_L{layer}_A_LOG"))
        parts.append(format_float_array(d_param, f"MAMBA_L{layer}_D"))
        parts.append(format_float_array(w_outproj, f"MAMBA_L{layer}_W_OUTPROJ"))

    # LayerNorm & Heads
    parts.append("/* Final LayerNorm & Prediction Heads */")
    parts.append(format_float_array(weights["model.ln_f.weight"], "MAMBA_LN_W"))
    parts.append(format_float_array(weights["model.ln_f.bias"], "MAMBA_LN_B"))
    parts.append(format_float_array(weights["onnx::MatMul_309"], "MAMBA_W_HEAD_BRANCH"))
    parts.append(format_float_array(weights["model.head_branch.bias"], "MAMBA_B_HEAD_BRANCH"))
    parts.append(format_float_array(weights["onnx::MatMul_310"], "MAMBA_W_HEAD_PC"))
    parts.append(format_float_array(weights["model.head_pc.bias"], "MAMBA_B_HEAD_PC"))

    parts.append("#endif /* MAMBA_NANO_WEIGHTS_H */")

    OUT_HEADER.write_text("\n".join(parts), encoding="utf-8")
    print(f"Successfully generated {OUT_HEADER} ({OUT_HEADER.stat().st_size / 1024:.1f} KB).")

if __name__ == "__main__":
    main()
